//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectKService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardScan
    {
        public CardScan()
        {
            this.CardScanResults = new HashSet<CardScanResult>();
        }
    
        public long CardScanID { get; set; }
        public string CardID { get; set; }
        public System.DateTime ScanDate { get; set; }
    
        public virtual ICollection<CardScanResult> CardScanResults { get; set; }
    }
}
