//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectKService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardScanResult
    {
        public CardScanResult()
        {
            this.VendingRequests = new HashSet<VendingRequest>();
        }
    
        public long CardScanResultID { get; set; }
        public long CardScanID { get; set; }
        public string CardBatch { get; set; }
        public string CardNumber { get; set; }
        public string CardFirstName { get; set; }
        public string CardLastName { get; set; }
        public System.DateTime ResultDate { get; set; }
        public string Status { get; set; }
    
        public virtual CardScan CardScan { get; set; }
        public virtual ICollection<VendingRequest> VendingRequests { get; set; }
    }
}
