//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectKService.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class klick_vending_machineEntities : DbContext
    {
        public klick_vending_machineEntities()
            : base("name=klick_vending_machineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CardScan> CardScans { get; set; }
        public DbSet<CardScanResult> CardScanResults { get; set; }
        public DbSet<Error> Errors { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<VendingRequest> VendingRequests { get; set; }
        public DbSet<Config> Configs { get; set; }
    }
}
